name: Write findings to CSV file

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 * * * *' # Run every hour at 00 minutes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pandas openpyxl
          sudo apt-get -y install wkhtmltopdf

      - name: create filename for findings file with current time & date-1
        run: |
          echo "CURRENT_DATE=$(date +'%H-%M--%d-%b-%Y')" >> $GITHUB_ENV
          echo "TEMP_STR=Findings" >> $GITHUB_ENV
    
      - name: create filename for findings file with current time & date-3
        run: |
          echo "FILENAME=$TEMP_STR-$CURRENT_DATE.csv" >> $GITHUB_ENV
          echo "FILENAMEHTML=$TEMP_STR-$CURRENT_DATE.html" >> $GITHUB_ENV
          echo "FILENAMEXLSX=$TEMP_STR-$CURRENT_DATE.xlsx" >> $GITHUB_ENV
          echo "FILENAMEPDF=$TEMP_STR-$CURRENT_DATE.pdf" >> $GITHUB_ENV
      
      - name: Troubleshooting 
        run: |
          echo "$CURRENT_DATE"
          echo "$TEMP_STR"
          echo "$FILENAME"
          echo "$FILENAMEHTML"
          echo "$FILENAMEXLSX"
          echo "$FILENAMEPDF"
          
      - name: execute py script # run main.py
        env:
          SEMGREP_API_WEB_TOKEN: ${{ secrets.SEMGREP_API_WEB_TOKEN }}
        run: |
          python3 main.py -r "DigitalInnovation/Semgrep_POC_fesk-pdp"

      - name: copy output.csv to $FILENAME.csv & output.html to $FILENAME.html & output.xlsx to $FILENAME.xlsx
        run: |
          cp DigitalInnovation_Semgrep_POC_fesk_pdp.csv $FILENAME
          cp DigitalInnovation_Semgrep_POC_fesk_pdp.html $FILENAMEHTML
          cp DigitalInnovation_Semgrep_POC_fesk_pdp.xlsx $FILENAMEXLSX
          cp DigitalInnovation_Semgrep_POC_fesk_pdp.pdf $FILENAMEPDF

      - name: Upload findings as Artifact- CSV     
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.FILENAME }}
          path: ${{ env.FILENAME }}
          
      - name: Upload findings as Artifact- HTML   
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.FILENAMEHTML }}
          path: ${{ env.FILENAMEHTML }}

      - name: Upload findings as Artifact- XLSX  
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.FILENAMEXLSX }}
          path: ${{ env.FILENAMEXLSX }}
          
      - name: Upload findings as Artifact- PDF  
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.FILENAMEPDF }}
          path: ${{ env.FILENAMEPDF }}      
