on: 
  workflow_dispatch: 
  push:
    branches:
    - main
    - master
    paths:
    - .github/workflows/semgrep.yml
#   schedule:
#   # random HH:MM to avoid a load spike on GitHub Actions at 00:00
#   - cron: 00 5 * * 1
name: Semgrep
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
      - uses: actions/checkout@v3
      - run: semgrep ci --oss-only --json --output findings.json
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import os
            print("Directory contents:")
            for f in os.listdir():
                print(f)

