    name: Semgrep
    
    on:
    # Scan changed files in PRs (diff-aware scanning):
     pull_request: {}
    # Scan on-demand through GitHub Ations interface:
     workflow_dispatch: {}
    # Scan main branches and report all findings:
     push:
            
    jobs:
     call-semgrep:
      uses: DigitalInnovation/semgrep-appsec-workflow/.github/workflows/semgrep_webapps.yml@main
      secrets:
       SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
